### ISSUE TITLE
Authentication and Encryption

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid-zmq#35]
In early analysis of 0MQ security underlying DCell, it seems the best way to bring authentication and encryption to DCell is by implementing CurveZMQ:

https://github.com/zeromq/libcurve

Research the API; if possible and wise: integrate libcurve to provide security for DCell.

- [x] Research API
- [x] Write integration
- [ ] Test implementation
- [ ] Write applicable tests
- [ ] Update documentation
- [x] Write example code

Coverage:

- [ ] Encryption
- [ ] Authentication

**Comment by Asmod4n** [comment]
czmq is about to get official ruby bindings, so my wrapper won't receive any updates anymore: https://github.com/zeromq/czmq/tree/master/bindings/ruby/lib/czmq/ffi

**Comment by digitalextremist** [comment]
Will reapproach once bindings land.
