### ISSUE TITLE
release 0.17

### ISSUE THREAD

**Issue by niamster** [celluloid/celluloid-zmq#42]
I propose to release 0.17 as at this point the master branch is quite stable

**Comment by digitalextremist** [comment]
@niamster I am good with that. I'd like to do a bit of testing, in particular try it with `celluloid-0.17.0` prerelease and push a `pre1` of this release until the release of `celluloid` also lands, then we bump both over to `0.17.0` - what do you think?

**Comment by tarcieri** [comment]
If nothing else it would be good to update the gemspec and version on master to reflect that the current codebase is 0.17.0.pre... and after you do that, probably just cut a pre.

**Comment by digitalextremist** [comment]
We need to update the tests to a higher version of rspec.

**Comment by digitalextremist** [comment]
Running `transpec` on it and looking at the failing tests.

**Comment by digitalextremist** [comment]
@niamster the tests are outdated. Just running `transpec` didn't fix them. I feel like we should have the mandatory cases green at least before cutting even a prerelease gem. I'd do this right now myself, but I am working on `0.17.0` of `celluloid` -- but I can come back to this if no one else is able to get on this.

**Comment by niamster** [comment]
@digitalextremist let me help you with that. I'll update the tests

**Comment by digitalextremist** [comment]
Sweet. Thanks @niamster

**Comment by niamster** [comment]
@digitalextremist PR #43 is ready

**Comment by digitalextremist** [comment]
Right on! Heading back to my desk in 60-90 minutes and I'll go through that. Thanks again @niamster

**Comment by niamster** [comment]
@digitalextremist I think #45 can be "safely" merged now.

**Comment by digitalextremist** [comment]
@niamster even without `0.17.0` of `celluloid` itself?

**Comment by digitalextremist** [comment]
@niamster I found a few things and noted those on the individual lines. The question is: should `master` of `celluloid-io` depend on `0.17.0-prerelease` of `celluloid` right away? I still need at least two more days before I'd say that's wise. Even then, I'd like to push a `0.17.0.pre1` of `celluloid-zmq` with these sorts of changes... how about that?

**Comment by niamster** [comment]
ah, you are right. I thought that we have 0.17.0-prerelease here. I agree that celluloid-xxx master branches should be synchronous.

**Comment by digitalextremist** [comment]
@niamster agreed, let's synchronize the versions. Feel free to bring #45 back in against a `0.17.0-prerelease` branch of `celluloid-zmq` instead of master

**Comment by digitalextremist** [comment]
I will update #48 to be `0.17.0` instead of `0.16.5` in light of this.

**Comment by digitalextremist** [comment]
Especially to resolve the issues coming up in DCell, I am going to cut this in the next day or so, but as `0.17.0` to begin synchronizing versions across the suite.
