### ISSUE TITLE
Assertion failed: check () (src/msg.cpp:248)

### ISSUE THREAD

**Issue by rfestag** [celluloid/celluloid-zmq#53]
I am trying to get even the examples to work on my desktop (Manjaro - with zmq-4.1.2-3 installed). I am able to run Celluloid::ZMQ.init, and include Celluloid::ZMQ in a class. However, as soon as I attempt to instantiate the class, I get the above assertion and my process exits.

Is celluloid-zmq compatible with zmq-4.1.2-3? If not, which versions is it compatible with? Any thoughts on how I can troubleshoot this issue?

**Comment by rfestag** [comment]
Some more details: the error appears to happen asynchronously. I get randomly far into the initializer before it crashes. In a simple test like this though, it still fails:

```ruby
require 'celluloid/zmq'
Celluloid::ZMQ.init
class Test
  include Celluloid::ZMQ
end
Test.new
sleep 1 #To give the failure a chance to happen. If you run in pry/irb, this is unnecessary
```
I'm seeing this behavior both in 0.16.1 and in 0.17.0 (built from 0.17.0-dependent).

**Comment by digitalextremist** [comment]
I will try `4.1.2` and get back to you. I am using `4.0.5`

A good person to engage on this is @chuckremes who wrote [ffi-rzmq](https://github.com/chuckremes/ffi-rzmq) which is much closer to the baremetal than `Celluloid::ZMQ`

**Comment by digitalextremist** [comment]
@rfestag did you try the earlier versions and it worked for you, just so I know? I have run your code in `pry` and have had no issue at the version I use.

**Comment by rfestag** [comment]
Good to know, I'll post there. I did go back and try an older version (3.2.5, which is the newest one I have easy access to before 4.1.2). That is working for me.

**Comment by digitalextremist** [comment]
Good.

This was reported: chuckremes/ffi-rzmq#121

**Comment by digitalextremist** [comment]
I am going to close this here, and let the issue continue there.

**Comment by rfestag** [comment]
Sounds good, thanks for taking a look.
