### ISSUE TITLE
How thread safety is handle by Celluloid-ZMQ with ffi-rzmq

### ISSUE THREAD

**Issue by gaurav-teliax** [celluloid/celluloid-zmq#63]
Fail to find a google group or an irc channel had resisted me to post the query over here.

Looking through the README code. I'm trying to understand how does Celluloid-zmq handle Thread Safety when used with `ffi-rzmq`.

Googling around I found this https://stackoverflow.com/questions/38773624/thread-issue-in-zeromq-ruby

But no concrete answer for it. 

I see the Celluloid-zmq is moved to CZMQ but we are using the version that still uses `ffi-rzmq` support.

**Comment by Asmod4n** [comment]
Don't share sockets between threads, thats all there is to it.
